### PR TITLE
Re-use environment for compilation

### PR DESCRIPTION
**Pull request by Pieter12345**
This is an optimization which uses the same environment to compile multiple msa scripts, rather than creating a new environment every time. Environment creation reads and parses a few files, so this is an expensive operation.

### CODE REVIEW

**Comment by LadyCailin** [comment]
Just to recap our discussion on discord - the solution here is to break out the expensive, relatively "static" parts of the environment into their own environment, which is only regenerated at explicit points. Then creating new Compiler/Global envs is much cheaper, and we can keep better separation of concerns there.

**Comment by Pieter12345** [comment]
I've made the adjustments. The build is failing due to Bukkit adding a new method to an interface which CH doesn't implement, that's unaffected by my changes.

**Comment by LadyCailin** [comment]
I fixed that yesterday, merge in from master

**Comment by Pieter12345** [comment]
Rebased onto master.

**Pull request merged**
