### PR TITLE
Don't trigger a player_teleport event if it was caused by an NPC

### PR DESCRIPTION
**Pull request by Murreey**

### CODE REVIEW

**Comment by PseudoKnight** [comment]
"instanceof NPC" is unnecessary as those would not trigger player_teleport.

**Comment by Murreey** [comment]
@PseudoKnight Oh, duh. Have removed it now.

**Comment by PseudoKnight** [comment]
I'm not sure this is something we should add in CH directly since it can be done in scripts when desired. Also, apparently Citizens adds metadata on a delay, so it wouldn't work in some cases. Check the edit [here](http://dev.enginehub.org/youtrack/issue/WORLDGUARD-3749).

**Comment by Murreey** [comment]
You can work around it with scripts but surely it'd be better for only players to trigger the player teleport event, as that's bound to trip a lot of people up. I guess it could also be solved in Spigot assuming that's related.

And the metadata seems to be fine (or at least gets added before they trigger the teleport event). It's not triggering even though Citizens loads after CH, or with a /citizens reload.

**Comment by LadyCailin** [comment]
I think this is fine. "player" does imply non-npc, so.. Further thoughts?

**Comment by jb-aero** [comment]
"Further thoughts": doesn't need the NPC import.

**Comment by PseudoKnight** [comment]
Another thought: What other events do NPCs trigger?

**Comment by Murreey** [comment]
Far as I can tell they also trigger world_changed if you TP them to a different world. Nothing of the other obvious ones like player_move or player_spawn trigger, but I'm not sure if there's a way to make them fish or use beds or anything more obscure.

They also trigger the region_change in CHWorldGuard when teleported, as it uses onPlayerTeleport too. That'll need fixed separately I guess.

**Comment by PseudoKnight** [comment]
The number of events player NPCs affect is significant. I was working my way through them, but feel like maybe there should be some sort of singular way to fix this in the bound event triggering. Anyway, I'm trying to resolve old PRs, so to the tracker this goes.

http://dev.enginehub.org/youtrack/issue/CMDHELPER-3140

**Pull request closed without merging**
