### PR TITLE
Update to ASM 5.0

### PR DESCRIPTION
**Pull request by Techcable**
Supports Minecraft Servers that use Java 8
Needed for [TacoSpigot](https://github.com/TacoSpigot/TacoSpigot)

### CODE REVIEW

**Comment by LadyCailin** [comment]
Have you tested this and ensured that everything works? Notable tests include sudo() and running an extension.

**Comment by PhanaticD** [comment]
I will test it with a bunch of extensions and sudo and get back to you

**Comment by PhanaticD** [comment]
tested it and appears fine now

**Comment by LadyCailin** [comment]
This commit has made broken reading in jarInfo.ser, which is significantly increasing startup time. Please join the IRC channel and discuss this change with me. If I don't get time to investigate myself, I'm just going to revert these commits.

**Comment by LadyCailin** [comment]
I have reverted this PR for now, since it breaks the startup.

**Comment by LadyCailin** [comment]
If you wish to re-apply these changes quickly, then continue working from where this left off, run these two commands:

    git revert e09e4ef17d15a733f1a1b4a075339edfa0858fbd
    git revert b7bfa28d6d9b0c6e42f38fa7671dfd5cf686647e

**Pull request merged**
