### PR TITLE
'collisionrule' and 'deathmessagevisibility' options for teams & entity ai functions

### PR DESCRIPTION
**Pull request by macjuul**

### CODE REVIEW

**Comment by PseudoKnight** [comment]
Setting the AI was added March 26th, a few weeks after 1.9 (right before 1.9.2). It might be a good candidate have checks in BukkitMCLivingEntity if the Bukkit methods exist. Alternatively, we could check for 1.9.2 due to its close proximity and guarantee of compatibility. I'm not sure which is faster, but I've seen LadyCailin say checking if the method exists is "correct". In those cases, I would add a comment in which version it was added, though.

**Comment by macjuul** [comment]
Yes, I'll work on that soon. I also noticed the nametagvisibility still uses the old deprecated methods, so we might want to change that to use the same enums as these new options

**Comment by PseudoKnight** [comment]
Yes, as long as it continues to work on older versions.

**Comment by macjuul** [comment]
Do we need backwards compatibility for the old nametagvisibility values in the new builds as well?

**Comment by macjuul** [comment]
I'll also added version checking to the glide and glow methods

**Comment by PseudoKnight** [comment]
I can't support the last commit as it would break compatibility with scripts with almost no benefit. The rest looks good, though.

**Comment by macjuul** [comment]
Sorry I've been rather busy lately. I'll be fixing it up and probably submitting it in a new PR when I have the time

**Comment by macjuul** [comment]
Improved PR coming asap

**Pull request closed without merging**
