### PR TITLE
Add all_materials() function

### PR DESCRIPTION
**Pull request by EntryPointKR**
I really worried about where `getMaterialValues()` should be placed.
I refered `getEnchantmentValues` so I placed it in BukkitConverter.

### CODE REVIEW

**Comment by EntryPointKR** [comment]
My IDE did repositioning imports automatically.  I tried to revert them but it seems not bad. Should I revert?

**Comment by PseudoKnight** [comment]
The import repositioning is fine in this case.

One suggestion: add isLegacy() to MCMaterial and use that instead of startsWith("LEGACY_"). This should improve operation time.

**Comment by PseudoKnight** [comment]
I'd prefer to filter out legacy materials in the GetMaterialValues(), if you want to do that instead.

**Comment by EntryPointKR** [comment]
Thats nice

**Pull request merged**
